// <auto-generated />
using System;
using EbiosRM.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbiosRM.Api.Migrations
{
    [DbContext(typeof(EbiosDbContext))]
    [Migration("20260809144937_AjoutStatutEtude")]
    partial class AjoutStatutEtude
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_engine")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.BienSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteResponsable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("biens_support", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.Etude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perimetre")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VersionReferentielId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("etudes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.EvenementRedoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gravite")
                        .HasColumnType("integer");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("evenements_redoutes", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_evenements_redoutes_gravite", "\"Gravite\" >= 1 AND \"Gravite\" <= 4");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.ValeurMetier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteResponsable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("valeurs_metier", "core_engine");
                });
#pragma warning restore 612, 618
        }
    }
}
