// <auto-generated />
using System;
using System.Collections.Generic;
using EbiosRM.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbiosRM.Api.Migrations
{
    [DbContext(typeof(EbiosDbContext))]
    [Migration("20260829151628_AjoutBibliothequeCommunautaire")]
    partial class AjoutBibliothequeCommunautaire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_engine")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EbiosRM.Api.Modules.Audit.Domain.EntreeJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Chemin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StatutHttp")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId", "DateUtc");

                    b.ToTable("journal_audit", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.BienSupportBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntiteProprietaireTypique")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_biens_support", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.EvenementRedouteBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GraviteIndicative")
                        .HasColumnType("integer");

                    b.Property<string>("ImpactsTypes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_evenements_redoutes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.MesureBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Referentiel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_mesures", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.ModeOperatoireBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DifficulteTechniqueTypique")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ProbabiliteSuccesTypique")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_modes_operatoires", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.PartiePrenanteBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ConfianceTypique")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DependanceTypique")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionCategorie")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaturiteCyberTypique")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("PenetrationTypique")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Representant")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RolesEtAttentes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_parties_prenantes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.PublicationBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntiteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Masquee")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProprietaireId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublieLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeEntite")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.HasIndex("TypeEntite", "EntiteId")
                        .IsUnique();

                    b.ToTable("bibliotheque_publications", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.SourceRisqueBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionObjectifVise")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionSourceRisque")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MotivationTypique")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectifVise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<int?>("RessourcesTypiques")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRisque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_sources_risque", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.ValeurMetierBibliotheque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntiteProprietaireTypique")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NatureOuFinalite")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProprietaireId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("bibliotheque_valeurs_metier", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Collaboration.Domain.EtudeMembre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AjouteLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AjoutePar")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("EtudeId", "UtilisateurId")
                        .IsUnique();

                    b.ToTable("etude_membres", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.BienSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteProprietaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("biens_support", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.Etude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perimetre")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ProprietaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VersionReferentielId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("etudes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.EvenementRedoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gravite")
                        .HasColumnType("integer");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("evenements_redoutes", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_evenements_redoutes_gravite", "\"Gravite\" >= 1 AND \"Gravite\" <= 4");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SnapshotAtelier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContenuJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroAtelier")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId", "NumeroAtelier", "Version")
                        .IsUnique();

                    b.ToTable("snapshots_atelier", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SocleSecurite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId")
                        .IsUnique();

                    b.ToTable("socles_securite", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.ValeurMetier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteProprietaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("valeurs_metier", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.CheminAttaque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioStrategiqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ScenarioStrategiqueId");

                    b.ToTable("chemins_attaque", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.PlanTraitementRisque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId")
                        .IsUnique();

                    b.ToTable("plans_traitement_risque", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioDeRisque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccepteParDirection")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CheminAttaqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAcceptationUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GraviteResiduelle")
                        .HasColumnType("integer");

                    b.Property<string>("JustificationAcceptation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("JustificationNiveauRisqueInitial")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("JustificationNiveauRisqueResiduel")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NiveauRisqueInitialRetenu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NiveauRisqueResiduelCalcule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NiveauRisqueResiduelRetenu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NomProprietaireRisque")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NomSponsorExecutif")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NomValidateurSecurite")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VraisemblanceResiduelle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CheminAttaqueId")
                        .IsUnique();

                    b.HasIndex("EtudeId");

                    b.ToTable("scenarios_de_risque", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_scenarios_de_risque_gravite_residuelle", "\"GraviteResiduelle\" IS NULL OR (\"GraviteResiduelle\" >= 1 AND \"GraviteResiduelle\" <= 4)");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioOperationnel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheminAttaqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheminAttaqueId")
                        .IsUnique();

                    b.HasIndex("EtudeId");

                    b.ToTable("scenarios_operationnels", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioStrategique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoupleSourceRisqueObjectifViseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvenementRedouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoupleSourceRisqueObjectifViseId")
                        .IsUnique();

                    b.HasIndex("EtudeId");

                    b.ToTable("scenarios_strategiques", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.CoupleSourceRisqueObjectifVise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContexteVulnerabilite")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionObjectifVise")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionSourceRisque")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificationPertinence")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Motivation")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectifVise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PertinenceCalculee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PertinenceRetenue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Ressources")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRisque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("Theme");

                    b.ToTable("couples_sr_ov", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_couples_sr_ov_motivation", "\"Motivation\" >= 1 AND \"Motivation\" <= 4");

                            t.HasCheckConstraint("CK_couples_sr_ov_ressources", "\"Ressources\" >= 1 AND \"Ressources\" <= 4");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.PartiePrenante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Confiance")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfianceResiduelle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Dependance")
                        .HasColumnType("integer");

                    b.Property<int?>("DependanceResiduelle")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionCategorie")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificationDangerosite")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("JustificationDangerositeResiduelle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MaturiteCyber")
                        .HasColumnType("integer");

                    b.Property<int?>("MaturiteCyberResiduelle")
                        .HasColumnType("integer");

                    b.Property<double?>("NiveauDangerositeCalcule")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeResiduelCalcule")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeResiduelRetenu")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeRetenu")
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Penetration")
                        .HasColumnType("integer");

                    b.Property<int?>("PenetrationResiduelle")
                        .HasColumnType("integer");

                    b.Property<string>("Representant")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RolesEtAttentes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("parties_prenantes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Identity.Domain.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("MotDePasseHache")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateurs", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Suivi.Domain.IndicateurSuivi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Cible")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Sens")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("SeuilAlerte")
                        .HasColumnType("double precision");

                    b.Property<string>("Unite")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("indicateurs_suivi", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.ModeOperatoireBibliotheque", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.Bibliotheque.Domain.ActionElementaireBibliotheque", "Actions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("CibleBienSupport")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("ModeOperatoireBibliothequeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordre")
                                .HasColumnType("integer");

                            b1.Property<string>("Phase")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("TechniqueMitre")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("ModeOperatoireBibliothequeId");

                            b1.ToTable("bibliotheque_actions_elementaires", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("ModeOperatoireBibliothequeId");
                        });

                    b.Navigation("Actions");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Bibliotheque.Domain.PublicationBibliotheque", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.Bibliotheque.Domain.SignalementBibliotheque", "Signalements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreeLeUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Motif")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("PublicationBibliothequeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SignalePar")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PublicationBibliothequeId", "SignalePar")
                                .IsUnique();

                            b1.ToTable("bibliotheque_signalements", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("PublicationBibliothequeId");
                        });

                    b.Navigation("Signalements");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SocleSecurite", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.ReferentielApplicable", "Referentiels", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("CodeControle")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Etat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("EtatActuel")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<Guid>("SocleSecuriteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Theme")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("SocleSecuriteId");

                            b1.ToTable("referentiels_applicables", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("SocleSecuriteId");
                        });

                    b.Navigation("Referentiels");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.CheminAttaque", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.EvenementIntermediaire", "EvenementsIntermediaires", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CheminAttaqueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("Ordre")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PartiePrenanteId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CheminAttaqueId");

                            b1.ToTable("evenements_intermediaires", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("CheminAttaqueId");
                        });

                    b.Navigation("EvenementsIntermediaires");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.PlanTraitementRisque", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.MesureTraitementRisque", "Mesures", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Axe")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("CoutComplexite")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<DateTime>("CreeLeUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Echeance")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("FreinsEtDifficultes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("PlanTraitementRisqueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Responsable")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Statut")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<List<string>>("_codesConformite")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("codes_conformite");

                            b1.Property<List<Guid>>("_scenariosDeRisqueIds")
                                .IsRequired()
                                .HasColumnType("uuid[]")
                                .HasColumnName("scenarios_de_risque_ids");

                            b1.HasKey("Id");

                            b1.HasIndex("PlanTraitementRisqueId");

                            b1.ToTable("mesures_traitement_risque", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("PlanTraitementRisqueId");
                        });

                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioOperationnel", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ModeOperatoire", "ModesOperatoires", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("DifficulteTechnique")
                                .HasColumnType("integer");

                            b1.Property<string>("JustificationVraisemblance")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("ProbabiliteSucces")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ScenarioOperationnelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VraisemblanceRetenue")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ScenarioOperationnelId");

                            b1.ToTable("modes_operatoires", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioOperationnelId");

                            b1.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ActionElementaire", "ActionsElementaires", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("BienSupportId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)");

                                    b2.Property<Guid>("ModeOperatoireId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Phase")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("TechniqueMitre")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("BienSupportId");

                                    b2.HasIndex("ModeOperatoireId");

                                    b2.ToTable("actions_elementaires", "core_engine");

                                    b2.WithOwner()
                                        .HasForeignKey("ModeOperatoireId");
                                });

                            b1.Navigation("ActionsElementaires");
                        });

                    b.Navigation("ModesOperatoires");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.PartiePrenante", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.MesureEcosysteme", "Mesures", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreeLeUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("PartiePrenanteId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PartiePrenanteId");

                            b1.ToTable("mesures_ecosysteme", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("PartiePrenanteId");
                        });

                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.Suivi.Domain.IndicateurSuivi", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.Suivi.Domain.PointMesureIndicateur", "Points", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Commentaire")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("IndicateurSuiviId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Valeur")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("IndicateurSuiviId");

                            b1.ToTable("points_mesure_indicateur", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("IndicateurSuiviId");
                        });

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
