// <auto-generated />
using System;
using EbiosRM.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbiosRM.Api.Migrations
{
    [DbContext(typeof(EbiosDbContext))]
    [Migration("20260820013225_OverrideDangerosite")]
    partial class OverrideDangerosite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_engine")
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.BienSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteProprietaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("biens_support", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.Etude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perimetre")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatutAtelier4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VersionReferentielId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("etudes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.EvenementRedoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gravite")
                        .HasColumnType("integer");

                    b.Property<Guid>("ValeurMetierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ValeurMetierId");

                    b.ToTable("evenements_redoutes", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_evenements_redoutes_gravite", "\"Gravite\" >= 1 AND \"Gravite\" <= 4");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SnapshotAtelier1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContenuJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DateCreationUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId", "Version")
                        .IsUnique();

                    b.ToTable("snapshots_atelier1", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SocleSecurite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId")
                        .IsUnique();

                    b.ToTable("socles_securite", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.ValeurMetier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntiteProprietaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("valeurs_metier", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.CheminAttaque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioStrategiqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("ScenarioStrategiqueId");

                    b.ToTable("chemins_attaque", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioOperationnel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CheminAttaqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheminAttaqueId")
                        .IsUnique();

                    b.HasIndex("EtudeId");

                    b.ToTable("scenarios_operationnels", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioStrategique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoupleSourceRisqueObjectifViseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvenementRedouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoupleSourceRisqueObjectifViseId")
                        .IsUnique();

                    b.HasIndex("EtudeId");

                    b.ToTable("scenarios_strategiques", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.CoupleSourceRisqueObjectifVise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContexteVulnerabilite")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionObjectifVise")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionSourceRisque")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificationPertinence")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Motivation")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectifVise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PertinenceCalculee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PertinenceRetenue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Ressources")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRisque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.HasIndex("Theme");

                    b.ToTable("couples_sr_ov", "core_engine", t =>
                        {
                            t.HasCheckConstraint("CK_couples_sr_ov_motivation", "\"Motivation\" >= 1 AND \"Motivation\" <= 4");

                            t.HasCheckConstraint("CK_couples_sr_ov_ressources", "\"Ressources\" >= 1 AND \"Ressources\" <= 4");
                        });
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.PartiePrenante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Confiance")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfianceResiduelle")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreeLeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Dependance")
                        .HasColumnType("integer");

                    b.Property<int?>("DependanceResiduelle")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionCategorie")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EtudeId")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificationDangerosite")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("JustificationDangerositeResiduelle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MaturiteCyber")
                        .HasColumnType("integer");

                    b.Property<int?>("MaturiteCyberResiduelle")
                        .HasColumnType("integer");

                    b.Property<double?>("NiveauDangerositeCalcule")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeResiduelCalcule")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeResiduelRetenu")
                        .HasColumnType("double precision");

                    b.Property<double?>("NiveauDangerositeRetenu")
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Penetration")
                        .HasColumnType("integer");

                    b.Property<int?>("PenetrationResiduelle")
                        .HasColumnType("integer");

                    b.Property<string>("Representant")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RolesEtAttentes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EtudeId");

                    b.ToTable("parties_prenantes", "core_engine");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.SocleSecurite", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.Cadrage.ReferentielApplicable", "Referentiels", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("CodeControle")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Etat")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("EtatActuel")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<Guid>("SocleSecuriteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Theme")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("SocleSecuriteId");

                            b1.ToTable("referentiels_applicables", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("SocleSecuriteId");
                        });

                    b.Navigation("Referentiels");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.CheminAttaque", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.EvenementIntermediaire", "EvenementsIntermediaires", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CheminAttaqueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("Ordre")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PartiePrenanteId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CheminAttaqueId");

                            b1.ToTable("evenements_intermediaires", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("CheminAttaqueId");
                        });

                    b.Navigation("EvenementsIntermediaires");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ScenarioOperationnel", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ModeOperatoire", "ModesOperatoires", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("DifficulteTechnique")
                                .HasColumnType("integer");

                            b1.Property<int>("ProbabiliteSucces")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ScenarioOperationnelId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ScenarioOperationnelId");

                            b1.ToTable("modes_operatoires", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioOperationnelId");

                            b1.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.ScenariosDeRisque.ActionElementaire", "ActionsElementaires", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("BienSupportId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)");

                                    b2.Property<Guid>("ModeOperatoireId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Phase")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("BienSupportId");

                                    b2.HasIndex("ModeOperatoireId");

                                    b2.ToTable("actions_elementaires", "core_engine");

                                    b2.WithOwner()
                                        .HasForeignKey("ModeOperatoireId");
                                });

                            b1.Navigation("ActionsElementaires");
                        });

                    b.Navigation("ModesOperatoires");
                });

            modelBuilder.Entity("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.PartiePrenante", b =>
                {
                    b.OwnsMany("EbiosRM.Api.Modules.CoreEngine.Domain.SourcesRisque.MesureEcosysteme", "Mesures", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreeLeUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("PartiePrenanteId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PartiePrenanteId");

                            b1.ToTable("mesures_ecosysteme", "core_engine");

                            b1.WithOwner()
                                .HasForeignKey("PartiePrenanteId");
                        });

                    b.Navigation("Mesures");
                });
#pragma warning restore 612, 618
        }
    }
}
