namespace EbiosRM.Api.Modules.Bibliotheque.Domain;

/// <summary>
/// Les 93 mesures de l'Annexe A d'ISO/IEC 27001:2022 (détaillées dans
/// ISO/IEC 27002:2022). Source backend unique : réutilisée par
/// <see cref="CatalogueSysteme"/> (bibliothèque de mesures) et par
/// <see cref="Conformite.Domain.CatalogueConformite"/> (exigences de
/// conformité).
/// </summary>
public static class CatalogueIso27002
{
    public sealed record Controle(string Code, string Titre, string Theme);

    private static Controle C(string code, string titre, string theme) => new(code, titre, theme);

    public static readonly IReadOnlyList<Controle> Controles = new[]
    {
        C("A.5.1", "Politiques de sécurité de l’information", "Organisationnel"),
        C("A.5.2", "Rôles et responsabilités liés à la sécurité de l’information", "Organisationnel"),
        C("A.5.3", "Séparation des tâches", "Organisationnel"),
        C("A.5.4", "Responsabilités de la direction", "Organisationnel"),
        C("A.5.5", "Relations avec les autorités", "Organisationnel"),
        C("A.5.6", "Relations avec des groupes de spécialistes", "Organisationnel"),
        C("A.5.7", "Renseignement sur les menaces", "Organisationnel"),
        C("A.5.8", "Sécurité de l’information dans la gestion de projet", "Organisationnel"),
        C("A.5.9", "Inventaire des informations et autres actifs associés", "Organisationnel"),
        C("A.5.10", "Utilisation correcte des informations et autres actifs associés", "Organisationnel"),
        C("A.5.11", "Restitution des actifs", "Organisationnel"),
        C("A.5.12", "Classification des informations", "Organisationnel"),
        C("A.5.13", "Marquage des informations", "Organisationnel"),
        C("A.5.14", "Transfert des informations", "Organisationnel"),
        C("A.5.15", "Contrôle d’accès", "Organisationnel"),
        C("A.5.16", "Gestion des identités", "Organisationnel"),
        C("A.5.17", "Informations d’authentification", "Organisationnel"),
        C("A.5.18", "Droits d’accès", "Organisationnel"),
        C("A.5.19", "Sécurité de l’information dans les relations avec les fournisseurs", "Organisationnel"),
        C("A.5.20", "Prise en compte de la sécurité de l’information dans les accords fournisseurs", "Organisationnel"),
        C("A.5.21", "Gestion de la sécurité de l’information dans la chaîne d’approvisionnement TIC", "Organisationnel"),
        C("A.5.22", "Surveillance, revue et gestion des changements des services fournisseurs", "Organisationnel"),
        C("A.5.23", "Sécurité de l’information pour l’utilisation des services en nuage", "Organisationnel"),
        C("A.5.24", "Planification et préparation de la gestion des incidents de sécurité", "Organisationnel"),
        C("A.5.25", "Évaluation et décision relatives aux événements de sécurité", "Organisationnel"),
        C("A.5.26", "Réponse aux incidents de sécurité de l’information", "Organisationnel"),
        C("A.5.27", "Retour d’expérience sur les incidents de sécurité de l’information", "Organisationnel"),
        C("A.5.28", "Collecte de preuves", "Organisationnel"),
        C("A.5.29", "Sécurité de l’information pendant une perturbation", "Organisationnel"),
        C("A.5.30", "Préparation des TIC pour la continuité d’activité", "Organisationnel"),
        C("A.5.31", "Exigences légales, statutaires, réglementaires et contractuelles", "Organisationnel"),
        C("A.5.32", "Droits de propriété intellectuelle", "Organisationnel"),
        C("A.5.33", "Protection des enregistrements", "Organisationnel"),
        C("A.5.34", "Confidentialité et protection des données à caractère personnel", "Organisationnel"),
        C("A.5.35", "Revue indépendante de la sécurité de l’information", "Organisationnel"),
        C("A.5.36", "Conformité aux politiques, règles et normes de sécurité de l’information", "Organisationnel"),
        C("A.5.37", "Procédures d’exploitation documentées", "Organisationnel"),
        C("A.6.1", "Sélection des candidats", "Personnes"),
        C("A.6.2", "Termes et conditions du contrat de travail", "Personnes"),
        C("A.6.3", "Sensibilisation, apprentissage et formation à la sécurité de l’information", "Personnes"),
        C("A.6.4", "Processus disciplinaire", "Personnes"),
        C("A.6.5", "Responsabilités après la fin ou le changement d’un contrat de travail", "Personnes"),
        C("A.6.6", "Accords de confidentialité ou de non-divulgation", "Personnes"),
        C("A.6.7", "Travail à distance", "Personnes"),
        C("A.6.8", "Signalement des événements liés à la sécurité de l’information", "Personnes"),
        C("A.7.1", "Périmètres de sécurité physique", "Physique"),
        C("A.7.2", "Entrée physique", "Physique"),
        C("A.7.3", "Sécurisation des bureaux, des salles et des installations", "Physique"),
        C("A.7.4", "Surveillance de la sécurité physique", "Physique"),
        C("A.7.5", "Protection contre les menaces physiques et environnementales", "Physique"),
        C("A.7.6", "Travail dans les zones sécurisées", "Physique"),
        C("A.7.7", "Bureau propre et écran vide", "Physique"),
        C("A.7.8", "Emplacement et protection du matériel", "Physique"),
        C("A.7.9", "Sécurité des actifs hors des locaux", "Physique"),
        C("A.7.10", "Supports de stockage", "Physique"),
        C("A.7.11", "Services généraux", "Physique"),
        C("A.7.12", "Sécurité du câblage", "Physique"),
        C("A.7.13", "Maintenance du matériel", "Physique"),
        C("A.7.14", "Mise au rebut ou recyclage sécurisé du matériel", "Physique"),
        C("A.8.1", "Terminaux finaux des utilisateurs", "Technologique"),
        C("A.8.2", "Droits d’accès privilégiés", "Technologique"),
        C("A.8.3", "Restriction d’accès à l’information", "Technologique"),
        C("A.8.4", "Accès au code source", "Technologique"),
        C("A.8.5", "Authentification sécurisée", "Technologique"),
        C("A.8.6", "Gestion de la capacité", "Technologique"),
        C("A.8.7", "Protection contre les logiciels malveillants", "Technologique"),
        C("A.8.8", "Gestion des vulnérabilités techniques", "Technologique"),
        C("A.8.9", "Gestion de la configuration", "Technologique"),
        C("A.8.10", "Suppression des informations", "Technologique"),
        C("A.8.11", "Masquage des données", "Technologique"),
        C("A.8.12", "Prévention de la fuite de données", "Technologique"),
        C("A.8.13", "Sauvegarde des informations", "Technologique"),
        C("A.8.14", "Redondance des moyens de traitement de l’information", "Technologique"),
        C("A.8.15", "Journalisation", "Technologique"),
        C("A.8.16", "Activités de surveillance", "Technologique"),
        C("A.8.17", "Synchronisation des horloges", "Technologique"),
        C("A.8.18", "Utilisation de programmes utilitaires à privilèges", "Technologique"),
        C("A.8.19", "Installation de logiciels sur des systèmes en exploitation", "Technologique"),
        C("A.8.20", "Sécurité des réseaux", "Technologique"),
        C("A.8.21", "Sécurité des services réseau", "Technologique"),
        C("A.8.22", "Cloisonnement des réseaux", "Technologique"),
        C("A.8.23", "Filtrage web", "Technologique"),
        C("A.8.24", "Utilisation de la cryptographie", "Technologique"),
        C("A.8.25", "Cycle de vie du développement sécurisé", "Technologique"),
        C("A.8.26", "Exigences de sécurité des applications", "Technologique"),
        C("A.8.27", "Principes d’ingénierie et d’architecture système sécurisées", "Technologique"),
        C("A.8.28", "Codage sécurisé", "Technologique"),
        C("A.8.29", "Tests de sécurité au cours du développement et de la réception", "Technologique"),
        C("A.8.30", "Développement externalisé", "Technologique"),
        C("A.8.31", "Séparation des environnements de développement, de test et de production", "Technologique"),
        C("A.8.32", "Gestion des changements", "Technologique"),
        C("A.8.33", "Informations de test", "Technologique"),
        C("A.8.34", "Protection des systèmes d’information lors des tests d’audit", "Technologique"),
    };
}
