export interface ControleIso {
  code: string
  theme: string
  nom: string
}

export var THEMES_ISO = ['Organisationnel', 'Personnes', 'Physique', 'Technologique']

export var CATALOGUE_ISO_27001: ControleIso[] = [
  // A.5 -- Organisationnel (37)
  { code: 'A.5.1', theme: 'Organisationnel', nom: 'Politiques de sécurité de l\u2019information' },
  { code: 'A.5.2', theme: 'Organisationnel', nom: 'Rôles et responsabilités liés à la sécurité de l\u2019information' },
  { code: 'A.5.3', theme: 'Organisationnel', nom: 'Séparation des tâches' },
  { code: 'A.5.4', theme: 'Organisationnel', nom: 'Responsabilités de la direction' },
  { code: 'A.5.5', theme: 'Organisationnel', nom: 'Relations avec les autorités' },
  { code: 'A.5.6', theme: 'Organisationnel', nom: 'Relations avec des groupes de spécialistes' },
  { code: 'A.5.7', theme: 'Organisationnel', nom: 'Renseignement sur les menaces' },
  { code: 'A.5.8', theme: 'Organisationnel', nom: 'Sécurité de l\u2019information dans la gestion de projet' },
  { code: 'A.5.9', theme: 'Organisationnel', nom: 'Inventaire des informations et autres actifs associés' },
  { code: 'A.5.10', theme: 'Organisationnel', nom: 'Utilisation correcte des informations et autres actifs associés' },
  { code: 'A.5.11', theme: 'Organisationnel', nom: 'Restitution des actifs' },
  { code: 'A.5.12', theme: 'Organisationnel', nom: 'Classification des informations' },
  { code: 'A.5.13', theme: 'Organisationnel', nom: 'Marquage des informations' },
  { code: 'A.5.14', theme: 'Organisationnel', nom: 'Transfert des informations' },
  { code: 'A.5.15', theme: 'Organisationnel', nom: 'Contrôle d\u2019accès' },
  { code: 'A.5.16', theme: 'Organisationnel', nom: 'Gestion des identités' },
  { code: 'A.5.17', theme: 'Organisationnel', nom: 'Informations d\u2019authentification' },
  { code: 'A.5.18', theme: 'Organisationnel', nom: 'Droits d\u2019accès' },
  { code: 'A.5.19', theme: 'Organisationnel', nom: 'Sécurité de l\u2019information dans les relations avec les fournisseurs' },
  { code: 'A.5.20', theme: 'Organisationnel', nom: 'Prise en compte de la sécurité de l\u2019information dans les accords fournisseurs' },
  { code: 'A.5.21', theme: 'Organisationnel', nom: 'Gestion de la sécurité de l\u2019information dans la chaîne d\u2019approvisionnement TIC' },
  { code: 'A.5.22', theme: 'Organisationnel', nom: 'Surveillance, revue et gestion des changements des services fournisseurs' },
  { code: 'A.5.23', theme: 'Organisationnel', nom: 'Sécurité de l\u2019information pour l\u2019utilisation des services en nuage' },
  { code: 'A.5.24', theme: 'Organisationnel', nom: 'Planification et préparation de la gestion des incidents de sécurité' },
  { code: 'A.5.25', theme: 'Organisationnel', nom: 'Évaluation et décision relatives aux événements de sécurité' },
  { code: 'A.5.26', theme: 'Organisationnel', nom: 'Réponse aux incidents de sécurité de l\u2019information' },
  { code: 'A.5.27', theme: 'Organisationnel', nom: 'Retour d\u2019expérience sur les incidents de sécurité de l\u2019information' },
  { code: 'A.5.28', theme: 'Organisationnel', nom: 'Collecte de preuves' },
  { code: 'A.5.29', theme: 'Organisationnel', nom: 'Sécurité de l\u2019information pendant une perturbation' },
  { code: 'A.5.30', theme: 'Organisationnel', nom: 'Préparation des TIC pour la continuité d\u2019activité' },
  { code: 'A.5.31', theme: 'Organisationnel', nom: 'Exigences légales, statutaires, réglementaires et contractuelles' },
  { code: 'A.5.32', theme: 'Organisationnel', nom: 'Droits de propriété intellectuelle' },
  { code: 'A.5.33', theme: 'Organisationnel', nom: 'Protection des enregistrements' },
  { code: 'A.5.34', theme: 'Organisationnel', nom: 'Confidentialité et protection des données à caractère personnel' },
  { code: 'A.5.35', theme: 'Organisationnel', nom: 'Revue indépendante de la sécurité de l\u2019information' },
  { code: 'A.5.36', theme: 'Organisationnel', nom: 'Conformité aux politiques, règles et normes de sécurité de l\u2019information' },
  { code: 'A.5.37', theme: 'Organisationnel', nom: 'Procédures d\u2019exploitation documentées' },

  // A.6 -- Personnes (8)
  { code: 'A.6.1', theme: 'Personnes', nom: 'Sélection des candidats' },
  { code: 'A.6.2', theme: 'Personnes', nom: 'Termes et conditions du contrat de travail' },
  { code: 'A.6.3', theme: 'Personnes', nom: 'Sensibilisation, apprentissage et formation à la sécurité de l\u2019information' },
  { code: 'A.6.4', theme: 'Personnes', nom: 'Processus disciplinaire' },
  { code: 'A.6.5', theme: 'Personnes', nom: 'Responsabilités après la fin ou le changement d\u2019un contrat de travail' },
  { code: 'A.6.6', theme: 'Personnes', nom: 'Accords de confidentialité ou de non-divulgation' },
  { code: 'A.6.7', theme: 'Personnes', nom: 'Travail à distance' },
  { code: 'A.6.8', theme: 'Personnes', nom: 'Signalement des événements liés à la sécurité de l\u2019information' },

  // A.7 -- Physique (14)
  { code: 'A.7.1', theme: 'Physique', nom: 'Périmètres de sécurité physique' },
  { code: 'A.7.2', theme: 'Physique', nom: 'Entrée physique' },
  { code: 'A.7.3', theme: 'Physique', nom: 'Sécurisation des bureaux, des salles et des installations' },
  { code: 'A.7.4', theme: 'Physique', nom: 'Surveillance de la sécurité physique' },
  { code: 'A.7.5', theme: 'Physique', nom: 'Protection contre les menaces physiques et environnementales' },
  { code: 'A.7.6', theme: 'Physique', nom: 'Travail dans les zones sécurisées' },
  { code: 'A.7.7', theme: 'Physique', nom: 'Bureau propre et écran vide' },
  { code: 'A.7.8', theme: 'Physique', nom: 'Emplacement et protection du matériel' },
  { code: 'A.7.9', theme: 'Physique', nom: 'Sécurité des actifs hors des locaux' },
  { code: 'A.7.10', theme: 'Physique', nom: 'Supports de stockage' },
  { code: 'A.7.11', theme: 'Physique', nom: 'Services généraux' },
  { code: 'A.7.12', theme: 'Physique', nom: 'Sécurité du câblage' },
  { code: 'A.7.13', theme: 'Physique', nom: 'Maintenance du matériel' },
  { code: 'A.7.14', theme: 'Physique', nom: 'Mise au rebut ou recyclage sécurisé du matériel' },

  // A.8 -- Technologique (34)
  { code: 'A.8.1', theme: 'Technologique', nom: 'Terminaux finaux des utilisateurs' },
  { code: 'A.8.2', theme: 'Technologique', nom: 'Droits d\u2019accès privilégiés' },
  { code: 'A.8.3', theme: 'Technologique', nom: 'Restriction d\u2019accès à l\u2019information' },
  { code: 'A.8.4', theme: 'Technologique', nom: 'Accès au code source' },
  { code: 'A.8.5', theme: 'Technologique', nom: 'Authentification sécurisée' },
  { code: 'A.8.6', theme: 'Technologique', nom: 'Gestion de la capacité' },
  { code: 'A.8.7', theme: 'Technologique', nom: 'Protection contre les logiciels malveillants' },
  { code: 'A.8.8', theme: 'Technologique', nom: 'Gestion des vulnérabilités techniques' },
  { code: 'A.8.9', theme: 'Technologique', nom: 'Gestion de la configuration' },
  { code: 'A.8.10', theme: 'Technologique', nom: 'Suppression des informations' },
  { code: 'A.8.11', theme: 'Technologique', nom: 'Masquage des données' },
  { code: 'A.8.12', theme: 'Technologique', nom: 'Prévention de la fuite de données' },
  { code: 'A.8.13', theme: 'Technologique', nom: 'Sauvegarde des informations' },
  { code: 'A.8.14', theme: 'Technologique', nom: 'Redondance des moyens de traitement de l\u2019information' },
  { code: 'A.8.15', theme: 'Technologique', nom: 'Journalisation' },
  { code: 'A.8.16', theme: 'Technologique', nom: 'Activités de surveillance' },
  { code: 'A.8.17', theme: 'Technologique', nom: 'Synchronisation des horloges' },
  { code: 'A.8.18', theme: 'Technologique', nom: 'Utilisation de programmes utilitaires à privilèges' },
  { code: 'A.8.19', theme: 'Technologique', nom: 'Installation de logiciels sur des systèmes en exploitation' },
  { code: 'A.8.20', theme: 'Technologique', nom: 'Sécurité des réseaux' },
  { code: 'A.8.21', theme: 'Technologique', nom: 'Sécurité des services réseau' },
  { code: 'A.8.22', theme: 'Technologique', nom: 'Cloisonnement des réseaux' },
  { code: 'A.8.23', theme: 'Technologique', nom: 'Filtrage web' },
  { code: 'A.8.24', theme: 'Technologique', nom: 'Utilisation de la cryptographie' },
  { code: 'A.8.25', theme: 'Technologique', nom: 'Cycle de vie du développement sécurisé' },
  { code: 'A.8.26', theme: 'Technologique', nom: 'Exigences de sécurité des applications' },
  { code: 'A.8.27', theme: 'Technologique', nom: 'Principes d\u2019ingénierie et d\u2019architecture système sécurisées' },
  { code: 'A.8.28', theme: 'Technologique', nom: 'Codage sécurisé' },
  { code: 'A.8.29', theme: 'Technologique', nom: 'Tests de sécurité au cours du développement et de la réception' },
  { code: 'A.8.30', theme: 'Technologique', nom: 'Développement externalisé' },
  { code: 'A.8.31', theme: 'Technologique', nom: 'Séparation des environnements de développement, de test et de production' },
  { code: 'A.8.32', theme: 'Technologique', nom: 'Gestion des changements' },
  { code: 'A.8.33', theme: 'Technologique', nom: 'Informations de test' },
  { code: 'A.8.34', theme: 'Technologique', nom: 'Protection des systèmes d\u2019information lors des tests d\u2019audit' },
]
